### ISSUE TITLE
vertx'x Fs2StreamTest sometimes fails

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#1169]
Here's the stack trace:

```
[info] - should convert fs2 stream to read stream *** FAILED ***
19835
[info]   scala.MatchError: false (of class java.lang.Boolean)
19836
[info]   at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:344)
19837
[info]   at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:342)
19838
[info]   at sttp.tapir.server.vertx.streams.Fs2StreamTest$$anonfun$$nestedInanonfun$new$25$1.applyOrElse(Fs2StreamTest.scala:95)
19839
[info]   at sttp.tapir.server.vertx.streams.Fs2StreamTest$$anonfun$$nestedInanonfun$new$25$1.applyOrElse(Fs2StreamTest.scala:95)
19840
[info]   at as @ sttp.tapir.server.vertx.streams.fs2$$anon$1$$anon$2.handler(fs2.scala:76)
19841
[info]   at flatTap @ sttp.tapir.server.vertx.streams.Fs2StreamTest.internal$1(Fs2StreamTest.scala:54)
19842
[info]   at *> @ sttp.tapir.server.tests.ServerBasicTests.$anonfun$basicTests$30(ServerBasicTests.scala:90)
19843
[info]   at as @ sttp.tapir.server.vertx.streams.fs2$$anon$1$$anon$2.handler(fs2.scala:76)
19844
[info]   at flatTap @ sttp.tapir.server.vertx.streams.Fs2StreamTest.internal$1(Fs2StreamTest.scala:54)
19845
[info]   at *> @ sttp.tapir.server.tests.ServerBasicTests.$anonfun$basicTests$30(ServerBasicTests.scala:90)
19846
[info]   ...
```

**Comment by adamw** [comment]
@danilbykov maybe you'll have an idea what might be the cause :)

**Comment by danilbykov** [comment]
I will check today.

**Comment by adamw** [comment]
I'm still getting these errors occasionally:

```scala
[info] Fs2StreamTest:
29634
[info] Fs2ReadStreamCompatible
29635
[info] - should convert fs2 stream to read stream *** FAILED ***
29636
[info]   scala.MatchError: false (of class java.lang.Boolean)
29637
[info]   at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:344)
29638
[info]   at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:342)
29639
[info]   at sttp.tapir.server.vertx.streams.Fs2StreamTest$$anon$4.applyOrElse(Fs2StreamTest.scala:96)
29640
[info]   at sttp.tapir.server.vertx.streams.Fs2StreamTest$$anon$4.applyOrElse(Fs2StreamTest.scala:96)
29641
[info]   at as @ sttp.tapir.server.vertx.streams.fs2$$anon$1$$anon$1.handler(fs2.scala:79)
29642
[info]   at flatTap @ sttp.tapir.server.vertx.streams.Fs2StreamTest.internal$1(Fs2StreamTest.scala:54)
29643
[info]   at *> @ sttp.tapir.server.tests.ServerBasicTests.basicTests$$anonfun$20(ServerBasicTests.scala:91)
29644
[info]   at as @ sttp.tapir.server.vertx.streams.fs2$$anon$1$$anon$1.handler(fs2.scala:79)
29645
[info]   at flatTap @ sttp.tapir.server.vertx.streams.Fs2StreamTest.internal$1(Fs2StreamTest.scala:54)
29646
[info]   at *> @ sttp.tapir.server.tests.ServerBasicTests.basicTests$$anonfun$20(ServerBasicTests.scala:91)
29647
[info]   ...
```
