### ISSUE TITLE
[BUG] Play Swagger looking for /docs/sw.js which doesn't exists

### ISSUE THREAD

**Issue by gaeljw** [softwaremill/tapir#1361]
Tapir version: 0.18.0-M11

Scala version: 2.13.6

**Describe the bug**

When starting Tapir with Play Server Interpreter + Play Swagger for OpenAPI, I noticed the following error in the logs when accessing Swagger endpoint (`/docs`):

```
! @7k9oj51ko - Internal server error, for (GET) [/docs/sw.js] ->
 
Caused by: java.lang.NullPointerException: null
	at play.api.mvc.Results$Status.sendResource(Results.scala:609)
	at sttp.tapir.swagger.play.SwaggerPlay$$anonfun$routes$1.$anonfun$applyOrElse$2(SwaggerPlay.scala:65)
	at play.api.mvc.ActionBuilder.$anonfun$apply$13(Action.scala:321)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
	at play.api.mvc.ActionBuilder$$anon$8.invokeBlock(Action.scala:289)
	at play.api.mvc.ActionBuilder$$anon$8.invokeBlock(Action.scala:284)
	at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
	at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
```

This doesn't cause any issue but should probably be avoided.

Strangely I don't see the request to `/docs/sw.js` fired from my browser but I may have missed something.

**How to reproduce?**

_(I could provide a sample repo to reproduce if necessary)_

Setup a Tapir project with Play framework + Play Swagger.

**Additional information**

N/A

**Comment by bartekzylinski** [comment]
I couldn't reproduce this issue. 
Could you provide sample repo with reproducing example ?

**Comment by gaeljw** [comment]
Sure, just use https://github.com/gaeljw/tapir-play-sample, run `sbt run` and go to http://localhost:9000, you'll see the error in the logs.

**Comment by bartekzylinski** [comment]
Unfortunately I was unable to reproduce this error with the provided repo.
I have tried on versions 0.18.0-M11 (from issue), 0.18.0 (default in repo), 0.19.0-M1 (latest)

**Comment by gaeljw** [comment]
Well then i'm sorry for the time spent on this.

I do reproduce always but it seems it's only me in one browser because of some caching and another project where we do have this _sw.js_ file.
