### ISSUE TITLE
[BUG] StackOverflowError when decoding enum with derived Schema

### ISSUE THREAD

**Issue by kubukoz** [softwaremill/tapir#1506]
Tapir version: 0.19.0-M4

Scala version: 3.0.1 / 3.1.0-RC2

**Describe the bug**

What is the problem?

A `StackOverflowError` gets thrown when you call an endpoint like this:

```scala
  enum Base derives Codec.AsObject, Schema {
    case EmptyImage
    // even this case isn't necessary to reproduce the issue
    case ImageReference(hash: String)
  }

  infallibleEndpoint
    .in("run")
    .post
    .in(jsonBody[Base])
```

**How to reproduce?**

Run the full code (ready sbt project in https://github.com/kubukoz/tapir-sooe-repro):

```scala
//scalaVersion := "3.1.0-RC2"
//libraryDependencies ++= Seq(
//  "org.http4s" %% "http4s-ember-server" % "0.23.4",
//  "com.softwaremill.sttp.tapir" %% "tapir-http4s-server" % "0.19.0-M9",
//  "com.softwaremill.sttp.tapir" %% "tapir-json-circe" % "0.19.0-M9",
//)

package demo

import cats.effect.IO
import cats.effect.IOApp
import com.comcast.ip4s.host
import com.comcast.ip4s.port
import io.circe.Codec
import org.http4s.HttpRoutes
import org.http4s.ember.server.EmberServerBuilder
import org.http4s.implicits._
import sttp.tapir.Schema
import sttp.tapir.server.http4s.Http4sServerInterpreter

object Main extends IOApp.Simple {

  enum Base derives Codec.AsObject, Schema {
    case EmptyImage
    // even this case isn't necessary to reproduce the issue
    case ImageReference(hash: String)
  }

  def run: IO[Unit] =
    EmberServerBuilder
      .default[IO]
      .withHost(host"0.0.0.0")
      .withPort(port"8083")
      .withHttpApp {
        import sttp.tapir._
        import sttp.tapir.json.circe._

        Http4sServerInterpreter[IO]()
          .toRoutes(
            infallibleEndpoint
              .in("run")
              .post
              .in(jsonBody[Base])
              .serverLogicInfallible(IO.println(_))
          )
          .orNotFound
      }
      .build
      .useForever

}
```

Call the endpoint:

```bash
curl -X POST localhost:8083/run --data {"EmptyImage":{}} -H Content-Type: application/json
```

See this in stderr of the program:

<details>
<summary>Stack trace</summary>

```
[0m[31m[E][0m java.lang.StackOverflowError
[0m[31m[E][0m 	at demo.Main$Base$.ordinal(Main.scala:18)
[0m[31m[E][0m 	at demo.Main$Base$.ordinal(Main.scala:18)
[0m[31m[E][0m 	at demo.Main$Base$.$anonfun$2(Main.scala:18)
[0m[31m[E][0m 	at magnolia.SealedTrait$Subtype.isDefinedAt(interface.scala:95)
[0m[31m[E][0m 	at magnolia.SealedTrait.rec$1(interface.scala:74)
[0m[31m[E][0m 	at magnolia.SealedTrait.choose(interface.scala:78)
[0m[31m[E][0m 	at demo.Main$$anon$3.$anonfun$3(Main.scala:18)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
// this repeats
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
// 
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
```

</details>

**Additional information**

This still happens if:
- the Codec or Schema instances are provided as `implicit def`/`implicit val`/`implicit lazy val`/`given` in the companion object of the enum
- the Codec instance is written by hand

This doesn't happen if:
- `Base` is an output type
- `Base` is a sealed trait hierarchy (even with `derives Schema`)
- The codec fails decoding (you just get a failed response instead, and the app keeps running)

**Comment by adamw** [comment]
Simpler way to reproduce:

```
import sttp.tapir.Schema

object Main extends App {

  enum Base {
    case EmptyImage
  }

  Schema.derived[Base].applyValidation(Base.EmptyImage)
}
```

**Comment by adamw** [comment]
Yeah that's a problem with magnolia. Given:

```scala
enum Size:
  case S, M, L

  test("construct a Show instance for an enum") {
    val res = Show.derived[Size].show(Size.S)
    assertEquals(res, "S")
  }
```

the result is `Size`, not `S`. The child typeclasses are incorrect.

**Comment by kubukoz** [comment]
Can you transfer the issue to magnolia? (I think that's possible with github's UI)
