### ISSUE TITLE
[BUG] AkkaHttp RequestInterceptor does not modify the request as expected

### ISSUE THREAD

**Issue by slavaschmidt** [softwaremill/tapir#1902]
Tapir version: 0.19, 0.20.0

Scala version: 2.12.15

Description:
I need to write whole request and response into the logs. In order to be able to consume the request entity in both LoggerInterceptor and API definition, I defined a RequestInterceptor with sole purpose of making request entity strict and thus consumable multiple times. Despite having strict entity after the request inerceptor, the API fails to consume it with an error message `java.lang.IllegalStateException: Substream Source(EntitySource) cannot be materialized more than once`.

Relevant log entries, please mind the second line with an output from the interceptor:
```
class: com.test.StrictEntityRequestInterceptor
     message: Strict entity length: 1020
     thread: service-akka.actor.default-dispatcher-12
     timestamp: 2022-02-27T19:17:08.102Z


class: akka.event.slf4j.Slf4jLogger$$anonfun$receive$1
     exception: java.lang.IllegalStateException: Substream Source(EntitySource) cannot be materialized more than once
	at akka.stream.impl.fusing.SubSource$$anon$11.createMaterializedTwiceException(StreamOfStreams.scala:846)
	at akka.stream.impl.fusing.SubSource$$anon$11.<init>(StreamOfStreams.scala:816)
	at akka.stream.impl.fusing.SubSource.createLogic(StreamOfStreams.scala:812)
	at akka.stream.stage.GraphStage.createLogicAndMaterializedValue(GraphStage.scala:106)
	at akka.stream.stage.GraphStageWithMaterializedValue.createLogicAndMaterializedValue(GraphStage.scala:50)
	at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:705)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:503)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:452)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:444)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:746)
	at akka.stream.scaladsl.Source.runWith(Source.scala:118)
	at akka.stream.scaladsl.Source.runFold(Source.scala:132)
	at akka.http.scaladsl.unmarshalling.PredefinedFromEntityUnmarshallers.$anonfun$byteStringUnmarshaller$3(PredefinedFromEntityUnmarshallers.scala:16)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$.$anonfun$mapWithInput$3(Unmarshaller.scala:93)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at sttp.tapir.server.akkahttp.AkkaRequestBody.toRawFromEntity(AkkaRequestBody.scala:28)
	at sttp.tapir.server.akkahttp.AkkaRequestBody.toRaw(AkkaRequestBody.scala:23)
	at sttp.tapir.server.akkahttp.AkkaRequestBody.toRaw(AkkaRequestBody.scala:18)
	at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$decodeBody$1(ServerInterpreter.scala:126)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:61)
	at sttp.tapir.server.interpreter.ServerInterpreter.decodeBody(ServerInterpreter.scala:126)
	at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$tryServerEndpoint$9(ServerInterpreter.scala:109)
	at sttp.tapir.server.interpreter.ServerInterpreter$ResultOrValue.$anonfun$flatMap$2(ServerInterpreter.scala:191)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

     file: Slf4jLogger.scala
     level: ERROR
     line: 77
     logger: akka.actor.ActorSystemImpl
     message: Error during processing of request: 'Substream Source(EntitySource) cannot be materialized more than once'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
java.lang.IllegalStateException: Substream Source(EntitySource) cannot be materialized more than once
	at akka.stream.impl.fusing.SubSource$$anon$11.createMaterializedTwiceException(StreamOfStreams.scala:846)
	at akka.stream.impl.fusing.SubSource$$anon$11.<init>(StreamOfStreams.scala:816)
	at akka.stream.impl.fusing.SubSource.createLogic(StreamOfStreams.scala:812)
	at akka.stream.stage.GraphStage.createLogicAndMaterializedValue(GraphStage.scala:106)
	at akka.stream.stage.GraphStageWithMaterializedValue.createLogicAndMaterializedValue(GraphStage.scala:50)
	at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:705)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:503)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:452)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:444)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:746)
	at akka.stream.scaladsl.Source.runWith(Source.scala:118)
	at akka.stream.scaladsl.Source.runFold(Source.scala:132)
	at akka.http.scaladsl.unmarshalling.PredefinedFromEntityUnmarshallers.$anonfun$byteStringUnmarshaller$3(PredefinedFromEntityUnmarshallers.scala:16)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$.$anonfun$mapWithInput$3(Unmarshaller.scala:93)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at sttp.tapir.server.akkahttp.AkkaRequestBody.toRawFromEntity(AkkaRequestBody.scala:28)
	at sttp.tapir.server.akkahttp.AkkaRequestBody.toRaw(AkkaRequestBody.scala:23)
	at sttp.tapir.server.akkahttp.AkkaRequestBody.toRaw(AkkaRequestBody.scala:18)
	at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$decodeBody$1(ServerInterpreter.scala:126)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:61)
	at sttp.tapir.server.interpreter.ServerInterpreter.decodeBody(ServerInterpreter.scala:126)
	at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$tryServerEndpoint$9(ServerInterpreter.scala:109)
	at sttp.tapir.server.interpreter.ServerInterpreter$ResultOrValue.$anonfun$flatMap$2(ServerInterpreter.scala:191)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

     method: $anonfun$applyOrElse$1
     thread: service-akka.actor.default-dispatcher-13
     timestamp: 2022-02-27T19:17:08.113Z     
```

AkkaHttpOptions.scala:

```scala
package com.test

import akka.actor.ActorSystem
import sttp.tapir.server.akkahttp.AkkaHttpServerOptions

import java.time.Clock

class AkkaHttpOptions(clock: Clock, loggerDispatcherPath: String)(implicit as: ActorSystem) {
  val loggingInterceptor = new RequestResponseLogger(clock, as.dispatchers.lookup(loggerDispatcherPath))
  val requestInterceptor = new StrictEntityRequestInterceptor
  val customServerOptions: AkkaHttpServerOptions = AkkaHttpServerOptions.customInterceptors
    .decodeFailureHandler(FailureHandler.decodeFailureHandler)
    .addInterceptor(requestInterceptor)
    .addInterceptor(loggingInterceptor)
    .options
}
```

StrictEntityRequestInterceptor.scala
```scala
package com.test

import akka.http.scaladsl.model.RequestEntity
import akka.http.scaladsl.server.RequestContext
import akka.stream.Materializer
import org.slf4j.LoggerFactory
import sttp.model.{Header, Method, QueryParams, Uri}
import sttp.monad.MonadError
import sttp.tapir.model.{ConnectionInfo, ServerRequest}
import sttp.tapir.server.interceptor._

import scala.collection.immutable
import scala.concurrent.duration.{DurationInt, FiniteDuration}
import scala.concurrent.{Await, Future}

class StrictEntityRequestInterceptor(implicit fm: Materializer) extends RequestInterceptor[Future] {
  override def apply[B](responder: Responder[Future, B], requestHandler: EndpointInterceptor[Future] => RequestHandler[Future, B]): RequestHandler[Future, B] = {
    new RequestHandler[Future, B] {
      override def apply(nonStrict: ServerRequest)(implicit monad: MonadError[Future]): Future[RequestResult[B]] = {
        val request = RequestBuffer.prepareRequest(nonStrict)
        val next = requestHandler(EndpointInterceptor.noop)
        next(request)
      }
    }
  }
}

object RequestBuffer {
  private val logger = LoggerFactory.getLogger(getClass)

  val timeout: FiniteDuration = 5.seconds

  private def makeEntityStrict(implicit fm: Materializer): RequestEntity => RequestEntity = re =>
    Await.result(re.toStrict(timeout), timeout)

  def prepareRequest(request: ServerRequest)(implicit fm: Materializer): ServerRequest = {
    val sr = request.underlying match {
      case ctx: RequestContext if ctx.request.entity.isStrict =>
        ctx
      case ctx: RequestContext =>
        val akkaRequest = ctx.request.mapEntity(makeEntityStrict)
        ctx.withRequest(akkaRequest)
    }
    val strictRequest = new ServerRequest {
      override def protocol: String               = request.protocol
      override def connectionInfo: ConnectionInfo = request.connectionInfo
      override def underlying: RequestContext     = sr
      override def pathSegments: List[String]     = request.pathSegments
      override def queryParameters: QueryParams   = request.queryParameters
      override def method: Method                 = request.method
      override def uri: Uri                       = request.uri
      override def headers: immutable.Seq[Header] = request.headers
    }
    if (!strictRequest.underlying.request.entity.isStrict()) {
      logger.warn(s"Could not make entity strict: ${strictRequest.underlying.request}")
    } else {
      val body = strictRequest.underlying.request.entity.toStrict(timeout).value.get.get.data.utf8String
      logger.info(s"Strict entity length: ${body.length}")
    }
    strictRequest
  }
}
```

**Comment by adamw** [comment]
Ah ok my test body wasn't big enough :)

**Comment by slavaschmidt** [comment]
:) anything big enough or slow enough so that it is not buffered by akka http will do

**Comment by slavaschmidt** [comment]
Thank you for looking into this!

**Comment by slavaschmidt** [comment]
Thank you very much Adam for fixing this! I'd like to bring your attention to the fact that an introduction of `withUnderlying` method to the `ServerRequest` trait makes an anonymous backend-agnostic implementation impossible. Please consider the following implementation I have with 0.20.0:
```scala
val strictRequest = new ServerRequest {
	override def protocol: String               = request.protocol
	override def connectionInfo: ConnectionInfo = request.connectionInfo
	override def pathSegments: List[String]     = request.pathSegments
	override def queryParameters: QueryParams   = request.queryParameters
	override def method: Method                 = request.method
	override def uri: Uri                       = request.uri

	override def underlying: Any                = modifiedUnderlying
	override def headers: immutable.Seq[Header] = originalHeaders ++ deprecatedOverrides ++ hiddenHeaders

	override def withUnderlying(underlying: Any): ServerRequest = ???
}
```

**Comment by adamw** [comment]
@slavaschmidt as I understand you'd like to override the headers? Maybe the following would work then:

```
class ServerRequestOverrideHeaders(val headers: Seq[Header], delegate: ServerRequest) extends ServerRequest {
  override def method: Method = delegate.method
  override def uri: Uri = delegate.uri
  override def protocol: String = delegate.protocol
  override def connectionInfo: ConnectionInfo = delegate.connectionInfo
  override def underlying: Any = delegate.underlying
  override def pathSegments: List[String] = delegate.pathSegments
  override def queryParameters: QueryParams = delegate.queryParameters
  override def withUnderlying(underlying: Any): ServerRequest =
    new ServerRequestOverrideHeaders(headers, delegate.withUnderlying(underlying))
}
```

If it does, maybe it would make sense to include it in the main sources :)

**Comment by slavaschmidt** [comment]
Thank you, this is exactly how I did that! :) I was just thinking that you might be interested in the fact :)

**Comment by adamw** [comment]
@slavaschmidt See: https://github.com/softwaremill/tapir/pull/1938/files

**Comment by AlixBa** [comment]
Not sure it is "recent". Might be a change from 0.x to 1.x.
I haven't been able to reproduce it 100% of the time, it's kind of random on our CI. 
FTR we're using tapir through Caliban and its AkkaHttpInterpreter.
We're still trying to figure out where the issue is (might be on our side too).
