### ISSUE TITLE
[BUG] oneOfUsingField fails for case object enums

### ISSUE THREAD

**Issue by hochgi** [softwaremill/tapir#1950]
Tapir version: 1.0.0-M1

Scala version: 2.13.8

**Describe the bug**
oneOfUsingField fails for case object enums (works for strings)

**What is the problem?**
Compilation error for what seems to be a valid code:
```
[error] …/Base.scala:60:61: type mismatch;
[error]  found   : ee.type (with underlying type hochgi.repro.datatypes.YEnum)
[error]  required: Product with hochgi.repro.datatypes.YEnum with java.io.Serializable
[error]     Schema.oneOfUsingField[YConf, YEnum](_.kind, _.toString)(
[error]                                                             ^
```

**How to reproduce?**
I've extracted a minimal example from a real project here:
https://github.com/hochgi/tapir-coproducts-schema/blob/working-boilerplate/endpoints/src/main/scala/hochgi/repro/endpoints/Base.scala#L62-L99
simply replace commented out code with actual code (that was copied and adjusted from output when running with `TAPIR_LOG_GENERATED_CODE=true` and when `kind` type was string) and try to compile.

**Maybe you can provide code to reproduce the problem?**
https://github.com/hochgi/tapir-coproducts-schema/blob/working-boilerplate/endpoints/src/main/scala/hochgi/repro/endpoints/Base.scala#L62-L99
The relevant parts discussed in [gitter](https://gitter.im/softwaremill/tapir?at=6230afd00466b352a41d3c44):
(1)
```scala
sealed trait YEnum
object YEnum {
  case object Y1 extends YEnum
  case object Y2 extends YEnum
  case object Y3 extends YEnum

  def all: List[YEnum] = List(Y1, Y2, Y3)

  def unapply(y: String): Option[YEnum] = y.toLowerCase match {
    case "y1" => Some(Y1)
    case "y2" => Some(Y2)
    case "y3" => Some(Y3)
    case _ => None
  }
}
```
(2)
```scala
sealed trait YConf {
  def kind: YEnum
}
object YConf {
  final case class Y1Conf(size: Int) extends YConf {
    override def kind: YEnum = YEnum.Y1
  }

  final case class Y2Conf(name: String) extends YConf {
    override def kind: YEnum = YEnum.Y2
  }

  final case class Y3Conf(depth: Int, model: String) extends YConf {
    override def kind: YEnum = YEnum.Y3
  }
}
```
(3)
```scala
implicit val yEnumSchema: Schema[YEnum] = Schema
  .derivedEnumeration[YEnum](encode = Some(_.toString))
  .name(Schema.SName("YEnum"))
  .description("Definition for \"YEnum\" " + YEnum.all.map(_.toString).mkString("(", ", ", ")"))

implicit val yConfSchema: Schema[YConf] = {
  val y1ConfSchema: Schema[YConf.Y1Conf] =
    Schema
      .derived[YConf.Y1Conf]
      .name(Schema.SName("Y1Conf"))
  val y2ConfSchema: Schema[YConf.Y2Conf] =
    Schema
      .derived[YConf.Y2Conf]
      .name(Schema.SName("Y2Conf"))
  val y3ConfSchema: Schema[YConf.Y3Conf] =
    Schema
      .derived[YConf.Y3Conf]
      .name(Schema.SName("Y3Conf"))
  Schema.oneOfUsingField[YConf, YEnum](_.kind, _.toString)(
    YEnum.Y1 -> y1ConfSchema,
    YEnum.Y2 -> y2ConfSchema,
    YEnum.Y3 -> y3ConfSchema)
}
```

**Additional information**
Same code compiles just fine if I use `String` instead of case object enums:
(1) same
(2)
```scala
sealed trait YConf {
  def kind: String
}
object YConf {
  final case class Y1Conf(size: Int) extends YConf {
    override def kind: String = YEnum.Y1.toString
  }

  final case class Y2Conf(name: String) extends YConf {
    override def kind: String = YEnum.Y2.toString
  }

  final case class Y3Conf(depth: Int, model: String) extends YConf {
    override def kind: String = YEnum.Y3.toString
  }
}
```
(3)
```scala
implicit val yConfSchema: Schema[YConf] = {
  val y1ConfSchema: Schema[YConf.Y1Conf] = …

  val y2ConfSchema: Schema[YConf.Y2Conf] = …

  val y3ConfSchema: Schema[YConf.Y3Conf] = …

  Schema.oneOfUsingField[YConf, String](_.kind, identity[String])(
    YEnum.Y1.toString -> y1ConfSchema,
    YEnum.Y2.toString -> y2ConfSchema,
    YEnum.Y3.toString -> y3ConfSchema)
}
```
**ALSO**
And it's probably a different issue (though might be related, so worth mentioning), but using `oneOf` like I did generates the following openAPI YAML:
```yaml
    Y1Conf:
      required:
      - size
      type: object
      properties:
        size:
          type: integer
    Y2Conf:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    Y3Conf:
      required:
      - depth
      - model
      type: object
      properties:
        depth:
          type: integer
        model:
          type: string
    YConf:
      oneOf:
      - $ref: '#/components/schemas/Y1Conf'
      - $ref: '#/components/schemas/Y2Conf'
      - $ref: '#/components/schemas/Y3Conf'
      discriminator:
        propertyName: kind
        mapping:
          Y1: '#/components/schemas/Y1Conf'
          Y2: '#/components/schemas/Y2Conf'
          Y3: '#/components/schemas/Y3Conf'
```
it has a `discriminator` + `propertyName` for `YConf`, but non of the subclasses has `kind` declared as `required` nor does it appear in the `properties`.

**Comment by seglo** [comment]
I had a similar problem that I worked around by mixing in `Product` and `Serializable` into base enum type (a sealed trait). This worked until recently, but when I upgraded to `0.20.1` I get a runtime exception during validation.

```
java.lang.IndexOutOfBoundsException: 0
	at seglo.BaseEnum$SomeEnum$.productElement(BaseEnum.scala:11)
	at magnolia1.ReadOnlyParam$$anon$3.dereference(interface.scala:213)
	at sttp.tapir.generic.internal.SchemaMagnoliaDerivation.$anonfun$productSchemaType$3(SchemaMagnoliaDerivation.scala:38)
	at sttp.tapir.Schema.$anonfun$applyValidation$5(Schema.scala:190)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at sttp.tapir.Schema.applyValidation(Schema.scala:190)
	at sttp.tapir.Schema.$anonfun$applyValidation$11(Schema.scala:195)
	at scala.Option.map(Option.scala:230)
	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
	at sttp.tapir.Schema.applyValidation(Schema.scala:179)
	at sttp.tapir.Codec.$anonfun$decode$2(Codec.scala:62)
	at sttp.tapir.Mapping$.validate$1(Mapping.scala:91)
	at sttp.tapir.Mapping$.decode(Mapping.scala:101)
	at sttp.tapir.Codec.decode(Codec.scala:62)
	at sttp.tapir.Codec.decode$(Codec.scala:62)
	at sttp.tapir.Codec$$anon$6.decode(Codec.scala:472)
	at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$decodeBody$2(ServerInterpreter.scala:168)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
	at sttp.monad.FutureMonad.flatMap(MonadError.scala:136)
	at sttp.monad.FutureMonad.flatMap(MonadError.scala:132)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:61)
	at sttp.tapir.server.interpreter.ServerInterpreter.decodeBody(ServerInterpreter.scala:167)
	at sttp.tapir.server.interpreter.ServerInterpreter.decodeBody(ServerInterpreter.scala:147)
	at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$tryServerEndpoint$10(ServerInterpreter.scala:125)
	at sttp.tapir.server.interpreter.ServerInterpreter$ResultOrValue.$anonfun$flatMap$2(ServerInterpreter.scala:232)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by adamw** [comment]
Regarding the second part, see the openapi spec (https://swagger.io/specification/), search for "Discriminator object". There is no requirement that the discriminator property be part of the subtypes; as far as I understand the spec, the property is assumed to point to the subtype's name. So it's there in the payload, but not part of the schema of the subtypes.

**Comment by seglo** [comment]
I upgraded to `1.0.0-M4` (Scala `2.12.12`), but I'm still having the same problem as originally reported.

```
[error] /.../CreateOfferRequest.scala:38:103: type mismatch;
[error]  found   : ee.type (with underlying type com.seglo.model.OfferType)
[error]  required: com.seglo.model.OfferType with Product with Serializable
[error] Error occurred in an application involving default arguments.
[error]     Schema.oneOfUsingField[CreateOfferRequest, OfferType](_.`type`, _.entryName)(
```

where `OfferType` is a `sealed trait` with case object implementations.

**Comment by adamw** [comment]
@seglo Could you provide a full reproducing test case? I've added the above to the test suite, plus your error is slightly different than in the bug description. This is probably a separate bug (so would be best to open a new GH issue)

**Comment by seglo** [comment]
Sure thing!
