### ISSUE TITLE
[BUG] Failing validation of OneOf object in runtime

### ISSUE THREAD

**Issue by xeppaka** [softwaremill/tapir#1956]
Tapir version: 0.20.1, 1.0.0-M2

Scala version: 2.13.7

Failing validation of OneOf object in runtime

What is the problem?

Please take a look on the failing test `it should validate oneOf object`, line 154 at: https://github.com/xeppaka/tapir/commit/2479b1df03e4d3578164f57a965ab6fcd4174821

Test result:
```
[info] SchemaTest:
[info] test
[info] - should schema *** FAILED ***
[info]   java.lang.ClassCastException: class java.lang.String cannot be cast to class scala.Product (java.lang.String is in module java.base of loader 'bootstrap'; scala.Product is in unnamed module of loader sbt.internal.ScalaLibraryClassLoader @77ef1d7f)
[info]   at magnolia1.ReadOnlyParam$$anon$3.dereference(interface.scala:213)
[info]   at sttp.tapir.generic.internal.SchemaMagnoliaDerivation.$anonfun$productSchemaType$3(SchemaMagnoliaDerivation.scala:38)
[info]   at sttp.tapir.Schema.$anonfun$applyValidation$5(Schema.scala:190)
[info]   at scala.collection.immutable.List.flatMap(List.scala:293)
[info]   at sttp.tapir.Schema.applyValidation(Schema.scala:190)
[info]   at sttp.tapir.Schema.$anonfun$applyValidation$11(Schema.scala:195)
[info]   at scala.Option.map(Option.scala:242)
[info]   at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[info]   at sttp.tapir.Schema.$anonfun$applyValidation$6(Schema.scala:190)
[info]   at scala.Option.map(Option.scala:242)
```

**Comment by adamw** [comment]
Thanks for the test case :)
