### ISSUE TITLE
[BUG] NPE on manual SProduct definition

### ISSUE THREAD

**Issue by hochgi** [softwaremill/tapir#1978]
**Tapir version:** 1.0.0-M1 & 1.0.0-M4

**Scala version:** 2.13.8

**Describe the bug**
Puzzling NullPointerException on startup:
```
java.lang.NullPointerException
	at sttp.tapir.Schema.$anonfun$hasValidation$4(Schema.scala:220)
	at sttp.tapir.Schema.$anonfun$hasValidation$4$adapted(Schema.scala:220)
	at scala.collection.immutable.List.exists(List.scala:395)
	at sttp.tapir.Schema.$anonfun$hasValidation$3(Schema.scala:220)
	at sttp.tapir.Schema.$anonfun$hasValidation$3$adapted(Schema.scala:220)
	at scala.Option.exists(Option.scala:406)
	at sttp.tapir.Schema.$anonfun$hasValidation$1(Schema.scala:220)
	at sttp.tapir.Schema.$anonfun$hasValidation$1$adapted(Schema.scala:215)
	at scala.Option.exists(Option.scala:406)
	at sttp.tapir.Schema.hasValidation(Schema.scala:215)
	at sttp.tapir.Schema.$anonfun$hasValidation$2(Schema.scala:217)
	at sttp.tapir.Schema.$anonfun$hasValidation$2$adapted(Schema.scala:217)
	at scala.Option.exists(Option.scala:406)
	at sttp.tapir.Schema.$anonfun$hasValidation$1(Schema.scala:217)
	at sttp.tapir.Schema.$anonfun$hasValidation$1$adapted(Schema.scala:215)
	at scala.Option.exists(Option.scala:406)
	at sttp.tapir.Schema.hasValidation(Schema.scala:215)
	at sttp.tapir.Schema.$anonfun$hasValidation$4(Schema.scala:220)
	at sttp.tapir.Schema.$anonfun$hasValidation$4$adapted(Schema.scala:220)
	at scala.collection.immutable.List.exists(List.scala:395)
	at sttp.tapir.Schema.$anonfun$hasValidation$3(Schema.scala:220)
	at sttp.tapir.Schema.$anonfun$hasValidation$3$adapted(Schema.scala:220)
	at scala.Option.exists(Option.scala:406)
	at sttp.tapir.Schema.$anonfun$hasValidation$1(Schema.scala:220)
	at sttp.tapir.Schema.$anonfun$hasValidation$1$adapted(Schema.scala:215)
	at scala.Option.exists(Option.scala:406)
	at sttp.tapir.Schema.hasValidation(Schema.scala:215)
	at sttp.tapir.Schema.$anonfun$hasValidation$2(Schema.scala:217)
	at sttp.tapir.Schema.$anonfun$hasValidation$2$adapted(Schema.scala:217)
	at scala.Option.exists(Option.scala:406)
	at sttp.tapir.Schema.$anonfun$hasValidation$1(Schema.scala:217)
	at sttp.tapir.Schema.$anonfun$hasValidation$1$adapted(Schema.scala:215)
	at scala.Option.exists(Option.scala:406)
	at sttp.tapir.Schema.hasValidation(Schema.scala:215)
	at sttp.tapir.SchemaType$SProduct$$anonfun$1.applyOrElse(SchemaType.scala:94)
	at sttp.tapir.SchemaType$SProduct$$anonfun$1.applyOrElse(SchemaType.scala:93)
	at scala.collection.immutable.List.collect(List.scala:267)
	at sttp.tapir.SchemaType$SProduct.<init>(SchemaType.scala:93)
	at …[irrelevant private namespaces redacted]…
	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:120)
	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
	at akka.actor.typed.internal.InterceptorImpl$$anon$1.start(InterceptorImpl.scala:50)
	at akka.actor.typed.BehaviorInterceptor.aroundStart(BehaviorInterceptor.scala:55)
	at akka.actor.typed.internal.InterceptorImpl.preStart(InterceptorImpl.scala:73)
	at akka.actor.typed.internal.InterceptorImpl$.$anonfun$apply$1(InterceptorImpl.scala:30)
	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:120)
	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:275)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:131)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:107)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**How to reproduce?**
I'm not sure if I'll be able to provide a minimal reproducing code without exposing too much.
I have'nt really tracked down the root cause yet.
Our domain datatypes are simple, but frontend requirements led to us defining a lot of schemas and codecs manually.
The place where this happens is when we define manually a product schema:
```scala
type JSON = InternalJsonAST

implicit val someTypeSchema: Schema[SomeType] = {

  val subId = SProductField[SomeType, String](
    _name   = FieldName("id", "id"),
    _schema = Schema.schemaForString,
    _get    = r => Some(r.id))

  val subJSONs = SProductField[SomeType, List[JSON]](
    _name   = FieldName("jsons", "jsons"),
    _schema = listOfJsonSchema,
    _get    = r => Some(r.jsons))

  val subRegularCaseClasses = SProductField[SomeType, List[RegularCaseClass]](
    _name   = FieldName("caseClasses", "caseClasses"),
    _schema = listORegularCaseClassSchema,
    _get    = r => Some(r.caseClasses))

  val schemaType = try {
    // This line causes the NPE
    SchemaType.SProduct(List(subId, subJSONs, subRegularCaseClasses))
  } catch {
    case t: NullPointerException =>
      // ¯\_(ツ)_/¯
      throw t
  }

  Schema(schemaType, Some(Schema.SName("our.internal.namespace.SomeType")))
}
```

**Maybe you can provide code to reproduce the problem?**
I'll keep trying to reproduce using something minimal. Will update this issue if I'm able to do that.

**Additional information**
Some attempts I ruled out.
While debugging I noticed this val:
![screenshot of debug session](https://gist.githubusercontent.com/hochgi/e7157e3cae5165f5e46224331ce866f1/raw/d6e2eebfd5888784a45fffd30141009e523aebb3/tapir_npe.png)
And figured maybe NPE is a result of some uninitialized val, and figured it would be worth to try and define this as a `lazy val`.

So I cloned tapir, did just that, publish locally, and tried with a snapshot version where the only change was defining `fieldsWithValidation` as a `lazy val`.
It did not works. Caused some sort of deadlock. App didn't crashed, but server was not up. After a couple of minutes in zombie state I killed it.

I also tried [adding lots of debug prints and defensive code](https://github.com/hochgi/tapir/compare/master...defensive-code-and-debug-prints). It did not help me figure out the cause either.

**Comment by hochgi** [comment]
I think figured out the cause. same as:
https://github.com/softwaremill/tapir/issues/945

In our case, we have JSON AST structure.
There's of course a dual recursion of data types.

`Obj` contains a `Map[String, Json]`, and `Arr` has a `Vector[Json]`.
Both inherit `Json` of course.

The dual recursion caused the NPE.
I worked around it by mimicking what you did here:
https://github.com/softwaremill/tapir/blob/master/json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala#L41-L46

I don't fully understand how, or why it works, but it does.


As for this issue: as a user I would expect to get a nicer error, that would lead me to understand what I did wrong.
If this is possible, it would mean a much better user experience.
Also, maybe add to docs a section of "common pitfalls", saying something about this. I assume I'm not the only one  using recursive datatypes…

**Comment by adamw** [comment]
I'm not quite sure if that's the case as I don't have a reproducing example, but recursive data structures might cause the problems you describe. In such cases, when you are referencing a field during its initialisation (here I understand this is `Schema[Json]`), it is initially `null` due to how the JVM works (all fields in a class instance are `null` initially and are then set to their proper value).

Using a simple `Json` schema as you described is one way. If you'd like to have something richer (though for `Json` I don't think there's a need), you can  break the recursive structure by using `Schema.SRef(Json)` inside `Obj` and `Arr`.

I don't think a nicer error message is possible (as this is how the JVM works), but as for docs - sure, maybe you'd like to give it a try? I think https://github.com/softwaremill/tapir/blob/master/doc/endpoint/schemas.md should be the right place :)

**Comment by hochgi** [comment]
OK @adamw!
I'll give it a go over the weekend (both a minimal reproducing example, and PR for documentation)

**Comment by hochgi** [comment]
@adamw I wasn't able to reproduce exactly.
this is kind of similar structure to what we had:
https://github.com/hochgi/tapir-bug-repro/tree/dual-recursion-npe
instead of NullPointerException, you'll get a StackOverflow

And it really make sense why.
I'll close the issue, since I can't provide a minimal good example.
