### ISSUE TITLE
[BUG] zio-vertx has thread blocked

### ISSUE THREAD

**Issue by desavitsky** [softwaremill/tapir#2316]
Tapir version: zio-vertx 1.0.0

Scala version: 2.13.8

I have a recurring log warn message that says Thread Thread[vert.x-worker-thread-2,5,main] has been blocked for 7550600 ms, time limit is 60000 ms
with that stacktrace:
```io.vertx.core.VertxException: Thread blocked
	at java.base@17.0.3/java.lang.Object.wait(Native Method)
	at java.base@17.0.3/java.lang.Object.wait(Object.java:338)
	at app//zio.internal.OneShot.get(OneShot.scala:83)
	at app//zio.Runtime.$anonfun$unsafeRunAsyncCancelable$1(Runtime.scala:312)
	at app//zio.Runtime$$Lambda$709/0x0000000800e75918.apply(Unknown Source)
	at app//sttp.tapir.server.vertx.zio.VertxZioServerInterpreter$$anonfun$$nestedInanonfun$endpointHandler$11$1.$anonfun$applyOrElse$1(VertxZioServerInterpreter.scala:79)
	at app//sttp.tapir.server.vertx.zio.VertxZioServerInterpreter$$anonfun$$nestedInanonfun$endpointHandler$11$1$$Lambda$7040/0x0000000801b8d8c0.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$6743/0x0000000801b32fa0.handle(Unknown Source)
	at app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:101)
	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$6740/0x0000000801b326e0.run(Unknown Source)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)
```

don't know how to reproduce, I didn't notice any blocking call right before it blocked, if find out something, will add it

**Comment by desavitsky** [comment]
Oh, I figured out: I accidently get into recursion in ZIO.fail block
I have
case class Error(message: String)
object Error {
  def apply(id: String): Error = Error(s"${id} not found")
}

**Comment by desavitsky** [comment]
So, it's obviously my fault, closing the issue:)
