### ISSUE TITLE
[BUG] NoSuchMethodError in ZioHttpRequestBody.asByteArray

### ISSUE THREAD

**Issue by tjarvstrand** [softwaremill/tapir#2413]
Hi,

When using the new zio-http 2.0.0-RC11 release I'm seeing the following exception on all requests handled by my caliban zio-http service (which uses tapir under the hood):
```
java.lang.NoSuchMethodError: 'zio.ZIO zhttp.http.Request.body()'
	at sttp.tapir.server.ziohttp.ZioHttpRequestBody.asByteArray(ZioHttpRequestBody.scala:36)
	at sttp.tapir.server.ziohttp.ZioHttpRequestBody.toRaw(ZioHttpRequestBody.scala:22)
	at sttp.tapir.server.ziohttp.ZioHttpRequestBody.toRaw(ZioHttpRequestBody.scala:18)
	at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$decodeBody$1(ServerInterpreter.scala:170)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:61)
	at sttp.tapir.server.interpreter.ServerInterpreter.decodeBody(ServerInterpreter.scala:170)
	at sttp.tapir.server.interpreter.ServerInterpreter.decodeBody(ServerInterpreter.scala:145)
	at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$tryServerEndpoint$10(ServerInterpreter.scala:124)
	at sttp.tapir.server.interpreter.ServerInterpreter$ResultOrValue.$anonfun$flatMap$2(ServerInterpreter.scala:237)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:818)
```

Scala version: 2.13.8
tapir version: 1.0.6
zio version: 2.0.2
zio-http version: 2.0.0-RC11
caliban-zio-http version: 2.0.1

**Comment by adamw** [comment]
Yes we are working on updating ziohttp, see https://github.com/softwaremill/tapir/pull/2412 and https://github.com/softwaremill/tapir/pull/2407

**Comment by tjarvstrand** [comment]
ah, thanks!
