### ISSUE TITLE
[BUG] Using Refined Tapir integration leads to a macro error for OpenAPI

### ISSUE THREAD

**Issue by longliveenduro** [softwaremill/tapir#2535]
Tapir version: 1.1.3

Scala version: 3.2.0

Using Refined Tapir integration and using "Int Refined Positive" in a schema leads to a macro big 

```
[error] -- Error: /home/chris/prj/toil/zio-geolocation/modules/core/src/main/scala/com/tsystems/toil/geolocation/rest/CustomTapirOpenApiSchemas.scala:26:31 
[error]  26 |  given Schema[PositionHint] = Schema.oneOfWrapped[PositionHint]
[error]     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |Exception occurred while executing macro expansion.
[error]     |java.util.NoSuchElementException: None.get
[error]     |	at scala.None$.get(Option.scala:627)
[error]     |	at scala.None$.get(Option.scala:626)
[error]     |	at sttp.tapir.macros.SchemaCompanionMacros$.$anonfun$2(SchemaMacros.scala:247)
[error]     |	at scala.collection.immutable.List.map(List.scala:246)
[error]     |	at sttp.tapir.macros.SchemaCompanionMacros$.generateOneOfWrapped(SchemaMacros.scala:249)
[error]     |
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from SchemaMacros.scala:127

```

What is the problem?

Use Refined Tapir integration with Scala 3 and use "Int Refined Positive" in a schema.

Maybe you can provide code to reproduce the problem?

Using this in closed source, but will try to create a short example.
UPDATE: Unfortunately I cannot yet reproduce it with https://github.com/longliveenduro/zio-geolocation-tapir-tapir-starter/tree/TapirRefinedIssue2535

Although I am also using subtypes (Publication -> Book, Movie).
Any other ideas how what I may have to include to reproduce it?

UPDATE 2: 

It seems that ```given Schema[PositionHint] = Schema.oneOfWrapped[PositionHint]``` is not needed any more. If I comment it out, it compiles and the resulting OpenAPI doc looks good to me.

**Comment by rafalambrozewicz** [comment]
Hi @longliveenduro 

I think, that I've managed to reproduce the problem above in the following code snippet:

```scala
package com.softwaremill.playground.refined_tapir_macro_error

import eu.timepit.refined.api.Refined
import eu.timepit.refined.numeric.Positive
import sttp.tapir.{PublicEndpoint, Schema, endpoint, query, stringBody}
//import sttp.tapir.generic.auto.* // enables schema derivation
//import sttp.tapir.codec.refined.* // enables refined support

object Main {

  object Library {
    case class Author(name: String)
    case class Director(name: String)
    sealed trait Publication
    case class Book(title: String, year: Int Refined Positive, author: Author) extends Publication
    case class Movie(title: String, year: Int Refined Positive, director: Director) extends Publication
  }

  def main(args: Array[String]): Unit = {
    import Library._
    given Schema[Publication] = Schema.oneOfWrapped[Publication]
  }
}
```

while I use `sbt.build` config presented below:

```scala 
ThisBuild / organization := "com.softwaremill.playground"
ThisBuild / scalaVersion := "3.2.0"
ThisBuild / version      := "0.1.0-SNAPSHOT"

val tapirVersion = "1.1.3"

lazy val root = (project in file("."))
  .settings(
    name := "refined_tapir_macro_error",
    libraryDependencies ++= Seq(
      "com.softwaremill.sttp.tapir" %% "tapir-core" % tapirVersion,
      "com.softwaremill.sttp.tapir" %% "tapir-refined" % tapirVersion,
    )
  )
```

The code, as it is now, won't compile with the error described in the issue. To make it work we need to uncomment the imports responsible for schema derivation and refined support. It looks like the root cause of the problem is that schema derivation was not properly configured. Yet another problem is not a meaningful error message, so I need to fix this :-)
