### ISSUE TITLE
[BUG] streamBinaryBody Out of memory or Timeout was reached

### ISSUE THREAD

**Issue by thepiwo** [softwaremill/tapir#2856]
Tapir version: 1.2.12

Scala version: 3.2.2

**Describe the bug**

I'm trying to upload files via streams, forwarding the stream to zio-s3 as upload.
my endpoint includes: `.in(streamBinaryBody(ZioStreams)(CodecFormat.OctetStream()))`

*Using* `tapir-zio-http-server`

trying to upload a file bigger than available heap I receive: 
```
java.lang.OutOfMemoryError: Cannot reserve 67313664 bytes of direct buffer memory (allocated: 76906504, limit: 134217728)
	at java.base/java.nio.Bits.reserveMemory(Bits.java:178)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:332)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:701)
	at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:690)
	at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:226)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:144)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:129)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:396)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at io.netty.buffer.CompositeByteBuf.allocBuffer(CompositeByteBuf.java:1879)
	at io.netty.buffer.CompositeByteBuf.consolidate0(CompositeByteBuf.java:1758)
	at io.netty.buffer.CompositeByteBuf.consolidateIfNeeded(CompositeByteBuf.java:571)
	at io.netty.buffer.CompositeByteBuf.addComponent(CompositeByteBuf.java:266)
	at io.netty.buffer.CompositeByteBuf.addComponent(CompositeByteBuf.java:222)
	at io.netty.handler.codec.MessageAggregator.appendPartialContent(MessageAggregator.java:331)
	at io.netty.handler.codec.MessageAggregator.decode(MessageAggregator.java:296)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:291)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

trying with a (way) file smaller than my heap I see the full file size (100MB) is allocated in heap:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/6539235/233511992-bc3a232c-0221-4abd-b3a7-00e823b2f504.png"> with a gc root in io.netty

*And using* `tapir-http4s-server-zio` memory doesn't seem to be a limiting factor, but I receive `Error: Timeout was reached` in my client after 30s failing to find where that is coming from (maybe fs2 stream conversion?).

unsure if thats related:
```
zio.stream.ZChannel$ChannelFailure$1: null
	at zio.stream.ZChannel.reader$lzyINIT10$1$$anonfun$2(ZChannel.scala:913)
	at zio.stream.ZChannel$Fold$K.onExit(ZChannel.scala:1351)
	at zio.stream.internal.ChannelExecutor.$anonfun$3(ChannelExecutor.scala:217)
	at zio.stream.internal.ChannelExecutor.run$$anonfun$5(ChannelExecutor.scala:218)
	at zio.stream.internal.ChannelExecutor$.read$4(ChannelExecutor.scala:711)
	at zio.stream.internal.ChannelExecutor$.read$4$$anonfun$7(ChannelExecutor.scala:731)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1021)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:391)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:514)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:230)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:139)
	at zio.internal.ZScheduler$$anon$4.run(ZScheduler.scala:476)
```
**How to reproduce?**

"slowly" consume the stream, don't have a runnable example ready

**Comment by thepiwo** [comment]
Sorry if this is not the correct place to report this, please let me know, I felt it might be a problem with tapir as I couldn't find any existing issues in zio-http.

**Comment by thepiwo** [comment]
Thanks, I just checked with the latest release and assume the upgrade to ZIO HTTP 3.0.0-RC1 in tapir v1.2.13 seems to have resolved my issue, I will verify and either close this issue or provide a reproducible example.

**Comment by thepiwo** [comment]
Seems to be resolved, thanks for the release!
