### ISSUE TITLE
[BUG] `Schema.oneOfWrapped` does not compile in Scala 3 for both the `enum`s and `sealed trait`s 

### ISSUE THREAD

**Issue by nikololiahim** [softwaremill/tapir#3026]
Tapir version: 1.6.0

Scala version: 3.3.0

**Describe the bug**

What is the problem?

Schema derivation for enums and sealed traits fails to compile in Scala 3.

**How to reproduce?**

Compiling the following code:
```scala
//> using scala "3.3.0"
//> using dep "com.softwaremill.sttp.tapir::tapir-json-circe:1.6.0"

import sttp.tapir.*
import sttp.tapir.json.circe.*
import io.circe.Codec

enum Fruit derives Codec.AsObject:
  case Apple, Banana

given Schema[Fruit] = Schema.oneOfWrapped

val fruits = endpoint.post.in("fruits").in(jsonBody[Fruit])

@main def main(): Unit = println("")
```

fails with the error:
```scala
Main.scala:12:23: Exception occurred while executing macro expansion.
java.lang.AssertionError: assertion failed
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
	at scala.quoted.runtime.impl.QuotesImpl$reflect$TypeIdent$.apply(QuotesImpl.scala:1102)
	at scala.quoted.runtime.impl.QuotesImpl$reflect$TypeIdent$.apply(QuotesImpl.scala:1101)
	at sttp.tapir.macros.SchemaCompanionMacros$.$anonfun$2(SchemaMacros.scala:254)
	at scala.collection.immutable.List.map(List.scala:246)
	at sttp.tapir.macros.SchemaCompanionMacros$.generateOneOfWrapped(SchemaMacros.scala:264)

 [12:23]
```

**Additional information**
Substituting 
```scala
enum Fruit derives Codec.AsObject:
  case Apple, Banana
```
 with 
```scala
sealed trait Fruit
object Fruit:
  case object Apple extends Fruit
  case object Banana extends Fruit
given Codec[Fruit] = Codec.AsObject.derived
```
yields the same result.

**Comment by nikololiahim** [comment]
Minimised further:
```scala
//> using scala "3.3.0"
//> using dep "com.softwaremill.sttp.tapir::tapir-core:1.6.0"

import sttp.tapir.Schema
import sttp.tapir.generic.auto.*
enum Fruit:
  case Apple, Banana

given Schema[Fruit] = Schema.oneOfWrapped
```

**Comment by adamw** [comment]
Ah, the problem is with case objects / no-parameter cases in an `enum`.

That looks more like an [enumeration](https://tapir.softwaremill.com/en/latest/endpoint/enumerations.html), than a one-of schema. How would you see this represented as a schema - what's the value that the macro should generate? 

Hm maybe an empty product ...

**Comment by adamw** [comment]
I think an empty product is the only possiblity - that's what generated by #3061
