### ISSUE TITLE
[BUG] prometheus metrics can't be exposed with new client_java using promehteus bridge

### ISSUE THREAD

**Issue by gastonschabas** [softwaremill/tapir#3315]
Tapir version: `1.9.0` 

Scala version: `2.13.12` / `3.3.1`

**Describe the bug**

[tapir-prometheus-metrics](https://tapir.softwaremill.com/en/latest/server/observability.html#prometheus-metrics) depends on [prometheus simpleclient 0.16.0](https://github.com/softwaremill/tapir/blob/b3c662ae89a09fadf642d9e92296c8916634bba2/build.sbt#L1027) which was released on [Jun 15, 2022](https://mvnrepository.com/artifact/io.prometheus/simpleclient_common/0.16.0). Today there is a new [prometheus client for java](https://prometheus.github.io/client_java/) which is a complete rewrite of the underlying data model, and is **not backwards compatible** with releases **0.16.0** and older. There is no need to upgrade it because there is a [bridge](https://prometheus.github.io/client_java/migration/simpleclient/#migration-using-the-simpleclient-bridge) that forwards the metrics registered in the old collector to the new one.

Creating a new tapir project, adding observability and using the bridge to forward metrics from the old collector to the new one, throw the following error message

```shell
An Exception occurred while scraping metrics: java.lang.IllegalArgumentException: Counts in ClassicHistogramBuckets cannot be negative.
	at io.prometheus.metrics.model.snapshots.ClassicHistogramBuckets.validate(ClassicHistogramBuckets.java:147)
	at io.prometheus.metrics.model.snapshots.ClassicHistogramBuckets.sortAndValidate(ClassicHistogramBuckets.java:108)
	at io.prometheus.metrics.model.snapshots.ClassicHistogramBuckets.of(ClassicHistogramBuckets.java:53)
	at io.prometheus.metrics.model.snapshots.ClassicHistogramBuckets$Builder.build(ClassicHistogramBuckets.java:220)
	at io.prometheus.metrics.simpleclient.bridge.SimpleclientCollector.makeBuckets(SimpleclientCollector.java:310)
	at io.prometheus.metrics.simpleclient.bridge.SimpleclientCollector.convertHistogram(SimpleclientCollector.java:185)
	at io.prometheus.metrics.simpleclient.bridge.SimpleclientCollector.convert(SimpleclientCollector.java:86)
	at io.prometheus.metrics.simpleclient.bridge.SimpleclientCollector.collect(SimpleclientCollector.java:61)
	at io.prometheus.metrics.model.registry.MultiCollector.collect(MultiCollector.java:26)
	at io.prometheus.metrics.model.registry.PrometheusRegistry.scrape(PrometheusRegistry.java:72)
	at io.prometheus.metrics.exporter.common.PrometheusScrapeHandler.scrape(PrometheusScrapeHandler.java:112)
	at io.prometheus.metrics.exporter.common.PrometheusScrapeHandler.handleRequest(PrometheusScrapeHandler.java:53)
	at io.prometheus.metrics.exporter.httpserver.MetricsHandler.handle(MetricsHandler.java:43)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:851)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:818)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**How to reproduce?**

With the following `build.sbt` and `Main.scala` file is enough to reproduce it

- `build.sbt`

```scala
ThisBuild / version := "0.0.0"
ThisBuild / scalaVersion := "2.13.12"

lazy val root = (project in file("."))
  .settings(
    name := "tapir-prometheus-java-client",
    libraryDependencies ++= Seq(
      "org.apache.pekko"            %% "pekko-actor-typed"        % "1.0.1",
      "com.softwaremill.sttp.tapir" %% "tapir-pekko-http-server"  % "1.9.0",
      "com.softwaremill.sttp.tapir" %% "tapir-prometheus-metrics" % "1.9.0",
      "io.prometheus"  % "prometheus-metrics-simpleclient-bridge" % "1.0.0",
      "ch.qos.logback" % "logback-classic"                        % "1.4.11",
      "com.typesafe.scala-logging" %% "scala-logging"           % "3.9.5",
      "io.prometheus"               % "prometheus-metrics-core" % "1.0.0",
      "io.prometheus" % "prometheus-metrics-exporter-httpserver" % "1.0.0"
    ),
    fork := true
  )
```

- `Main.scala`

```scala
import io.prometheus.metrics.exporter.httpserver.HTTPServer
import io.prometheus.metrics.simpleclient.bridge.SimpleclientCollector
import org.apache.pekko.actor.typed.ActorSystem
import org.apache.pekko.actor.typed.scaladsl.Behaviors
import org.apache.pekko.http.scaladsl.Http
import org.apache.pekko.http.scaladsl.server.Route
import sttp.tapir._
import sttp.tapir.server.metrics.prometheus.PrometheusMetrics
import sttp.tapir.server.pekkohttp.{PekkoHttpServerInterpreter, PekkoHttpServerOptions}

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future

object Main {
  def main(args: Array[String]) : Unit = {

    SimpleclientCollector.builder().register() // registered the bridge

    implicit val system: ActorSystem[Nothing] =
      ActorSystem(Behaviors.empty, "money-maniacs-http")

    val baseEndpoint = endpoint.in("dummy")

    val dummyEndpoint = baseEndpoint.get.out(stringBody)

    val dummyServerEndpoint =
      dummyEndpoint.serverLogic[Future](_ => Future(Right("dummy response")))

    val prometheusMetrics: PrometheusMetrics[Future] =
      PrometheusMetrics.default[Future]()

    val pekkoOptions = PekkoHttpServerOptions.customiseInterceptors
      .appendInterceptor(prometheusMetrics.metricsInterceptor())
      .options

    // added the dummy endpoint and the prometheus metric endpoint
    val pekkoServer: Route =
      PekkoHttpServerInterpreter(pekkoOptions).toRoute(
        List(dummyServerEndpoint, prometheusMetrics.metricsEndpoint)
      )

    Http()
      .newServerAt(interface = "0.0.0.0", port = 9000)
      .bind(pekkoServer)

    // started the prometheus http server that exposes metrics in endpoint http://localhost:9400/metrics 
    HTTPServer
      .builder()
      .port(9400)
      .buildAndStart()
  }
}
```

**Additional information**

Instead of starting the prometheus exporter server in another port, a new endpoint with the corresponding codec can be added like it was done in `tapir-prometheus-metrics` and you will get the same internal server error.

- Add the following dependency

```scala
"io.prometheus" % "prometheus-metrics-exposition-formats"  % "1.0.0"
```

- Replace the main with the following code and it will expose new metrics in endpoint `/metrics-new`

```scala
import io.prometheus.metrics.expositionformats.ExpositionFormats
import io.prometheus.metrics.model.registry.PrometheusRegistry
import io.prometheus.metrics.simpleclient.bridge.SimpleclientCollector
import org.apache.pekko.actor.typed.ActorSystem
import org.apache.pekko.actor.typed.scaladsl.Behaviors
import org.apache.pekko.http.scaladsl.Http
import org.apache.pekko.http.scaladsl.server.Route
import sttp.monad.MonadError
import sttp.tapir.CodecFormat.TextPlain
import sttp.tapir._
import sttp.tapir.server.ServerEndpoint
import sttp.tapir.server.metrics.prometheus.PrometheusMetrics
import sttp.tapir.server.pekkohttp.{PekkoHttpServerInterpreter, PekkoHttpServerOptions}

import java.io.ByteArrayOutputStream
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future

object TapirMain {
  def main(args: Array[String]): Unit = {

    SimpleclientCollector.builder().register()

    implicit val system: ActorSystem[Nothing] =
      ActorSystem(Behaviors.empty, "money-maniacs-http")

    val baseEndpoint = endpoint.in("dummy")

    val dummyEndpoint = baseEndpoint.get.out(stringBody)

    val dummyServerEndpoint =
      dummyEndpoint.serverLogic[Future](_ => Future(Right("dummy response")))

    val prometheusMetrics: PrometheusMetrics[Future] =
      PrometheusMetrics.default[Future]()

    implicit val schemaForPrometheusRegistry: Schema[PrometheusRegistry] =
      Schema.string[PrometheusRegistry]

    implicit val prometheusRegistryCodec
      : Codec[String, PrometheusRegistry, CodecFormat.TextPlain] =
      Codec.anyString(TextPlain())(_ =>
        DecodeResult.Value(new PrometheusRegistry())
      )(r => {
        val output = new ByteArrayOutputStream()
        ExpositionFormats
          .init()
          .getPrometheusTextFormatWriter
          .write(output, r.scrape())
        output.close()
        output.toString
      })

    val prometheusMetricsEndpointNewRegistry = ServerEndpoint.public(
      endpoint.in("metrics-new").out(plainBody[PrometheusRegistry]),
      (monad: MonadError[Future]) =>
        (_: Unit) =>
          monad.eval(
            Right(PrometheusRegistry.defaultRegistry): Either[
              Unit,
              PrometheusRegistry
            ]
          )
    )

    val pekkoOptions = PekkoHttpServerOptions.customiseInterceptors
      .appendInterceptor(
        prometheusMetrics.metricsInterceptor(
          List(prometheusMetricsEndpointNewRegistry.endpoint)
        )
      )
      .options

    val pekkoServer: Route =
      PekkoHttpServerInterpreter(pekkoOptions).toRoute(
        List(
          dummyServerEndpoint,
          prometheusMetrics.metricsEndpoint,
          prometheusMetricsEndpointNewRegistry
        )
      )

    Http()
      .newServerAt(interface = "0.0.0.0", port = 9000)
      .bind(pekkoServer)

  }
}
```

**Workaround**

I tried to troubleshoot the error, but I couldn't understand if the issue comes from tapir or from the prometheus bridge. I was able to solve the problem upgrading the prometheus client library to `1.0.0` and applying the required refactoring to make it work. So I'm not sure if this should be reported as a bug or as a feature request.

This is what I did

- Removed `tapir-prometheus-metrics` from the dependency list and added the following ones

```scala
"io.prometheus" % "prometheus-metrics-core" % "1.0.0"
"io.prometheus" % "prometheus-metrics-exposition-formats" % "1.0.0"
```

- created a similar class to [PrometheusMetrics](https://github.com/softwaremill/tapir/blob/b3c662ae89a09fadf642d9e92296c8916634bba2/metrics/prometheus-metrics/src/main/scala/sttp/tapir/server/metrics/prometheus/PrometheusMetrics.scala#L15) following the [refactoring instructions](https://prometheus.github.io/client_java/migration/simpleclient/#refactoring-the-instrumentation-code) from the docs

> As long as you are using high-level metric API like `Counter`, `Gauge`, `Histogram`, and `Summary` converting code to the new API is relatively straightforward. You will need to adapt the package name and apply some minor changes like using `builder()` instead of `build()` or using `labelValues()` instead of `labels()`

and this was the result

```scala
import io.prometheus.metrics.core.metrics.{Counter, Gauge, Histogram}
import io.prometheus.metrics.expositionformats.ExpositionFormats
import io.prometheus.metrics.model.registry.PrometheusRegistry
import sttp.monad.MonadError
import sttp.tapir.CodecFormat.TextPlain
import sttp.tapir._
import sttp.tapir.server.ServerEndpoint
import sttp.tapir.server.interceptor.metrics.MetricsRequestInterceptor
import sttp.tapir.server.metrics.{EndpointMetric, Metric, MetricLabels}

import java.io.ByteArrayOutputStream
import java.time.{Clock, Duration}

case class PrometheusMetrics[F[_]](
  namespace: String = "tapir",
  registry: PrometheusRegistry = PrometheusRegistry.defaultRegistry,
  metrics: List[Metric[F, _]] = List.empty[Metric[F, _]],
  endpointPrefix: EndpointInput[Unit] = "metrics"
) {
  import PrometheusMetrics._

  /** An endpoint exposing the current metric values. */
  lazy val metricsEndpoint: ServerEndpoint[Any, F] = ServerEndpoint.public(
    endpoint.get.in(endpointPrefix).out(plainBody[PrometheusRegistry]),
    (monad: MonadError[F]) =>
      (_: Unit) => monad.eval(Right(registry): Either[Unit, PrometheusRegistry])
  )

  /** Registers a `$namespace_request_active{path, method}` gauge (assuming
    * default labels).
    */
  def addRequestsActive(
    labels: MetricLabels = MetricLabels.Default
  ): PrometheusMetrics[F] =
    copy(metrics = metrics :+ requestActive(registry, namespace, labels))

  /** Registers a `$namespace_request_total{path, method, status}` counter
    * (assuming default labels).
    */
  def addRequestsTotal(
    labels: MetricLabels = MetricLabels.Default
  ): PrometheusMetrics[F] =
    copy(metrics = metrics :+ requestTotal(registry, namespace, labels))

  /** Registers a `$namespace_request_duration_seconds{path, method, status,
    * phase}` histogram (assuming default labels).
    */
  def addRequestsDuration(
    labels: MetricLabels = MetricLabels.Default,
    clock: Clock = Clock.systemUTC()
  ): PrometheusMetrics[F] =
    copy(metrics =
      metrics :+ requestDuration(registry, namespace, labels, clock)
    )

  /** Registers a custom metric. */
  def addCustom(m: Metric[F, _]): PrometheusMetrics[F] =
    copy(metrics = metrics :+ m)

  /** The interceptor which can be added to a server's options, to enable
    * metrics collection.
    */
  def metricsInterceptor(
    ignoreEndpoints: Seq[AnyEndpoint] = Seq.empty
  ): MetricsRequestInterceptor[F] =
    new MetricsRequestInterceptor[F](
      metrics,
      ignoreEndpoints :+ metricsEndpoint.endpoint
    )
}

object PrometheusMetrics {

  implicit val schemaForPrometheusRegistry: Schema[PrometheusRegistry] =
    Schema.string[PrometheusRegistry]

  implicit val prometheusRegistryCodec
    : Codec[String, PrometheusRegistry, CodecFormat.TextPlain] =
    Codec.anyString(TextPlain())(_ =>
      DecodeResult.Value(new PrometheusRegistry())
    )(r => {
      val output = new ByteArrayOutputStream()
      ExpositionFormats
        .init()
        .getPrometheusTextFormatWriter
        .write(output, r.scrape())
      output.close()
      output.toString
    })

  /** Using the default namespace and labels, registers the following metrics:
    *
    *   - `$namespace_request_active{path, method}` (gauge)
    *   - `$namespace_request_total{path, method, status}` (counter)
    *   - `$namespace_request_duration_seconds{path, method, status, phase}`
    *     (histogram)
    *
    * Status is by default the status code class (1xx, 2xx, etc.), and phase can
    * be either `headers` or `body` - request duration is measured separately up
    * to the point where the headers are determined, and then once again when
    * the whole response body is complete.
    */
  def default[F[_]](
    namespace: String = "tapir",
    registry: PrometheusRegistry = PrometheusRegistry.defaultRegistry,
    labels: MetricLabels = MetricLabels.Default
  ): PrometheusMetrics[F] =
    PrometheusMetrics(
      namespace,
      registry,
      List(
        requestActive(registry, namespace, labels),
        requestTotal(registry, namespace, labels),
        requestDuration(registry, namespace, labels)
      )
    )

  def requestActive[F[_]](
    registry: PrometheusRegistry,
    namespace: String,
    labels: MetricLabels
  ): Metric[F, Gauge] =
    Metric[F, Gauge](
      Gauge
        .builder()
        .name(s"${namespace}_request_active")
        .help("Active HTTP requests")
        .labelNames(labels.namesForRequest: _*)
        .register(registry),
      onRequest = { (req, gauge, m) =>
        m.unit {
          EndpointMetric()
            .onEndpointRequest { ep =>
              m.eval(
                gauge.labelValues(labels.valuesForRequest(ep, req): _*).inc()
              )
            }
            .onResponseBody { (ep, _) =>
              m.eval(
                gauge.labelValues(labels.valuesForRequest(ep, req): _*).dec()
              )
            }
            .onException { (ep, _) =>
              m.eval(
                gauge.labelValues(labels.valuesForRequest(ep, req): _*).dec()
              )
            }
        }
      }
    )

  def requestTotal[F[_]](
    registry: PrometheusRegistry,
    namespace: String,
    labels: MetricLabels
  ): Metric[F, Counter] =
    Metric[F, Counter](
      Counter
        .builder()
        .name(s"${namespace}_request_total")
        .help("Total HTTP requests")
        .labelNames(labels.namesForRequest ++ labels.namesForResponse: _*)
        .register(registry),
      onRequest = { (req, counter, m) =>
        m.unit {
          EndpointMetric()
            .onResponseBody { (ep, res) =>
              m.eval(
                counter
                  .labelValues(
                    labels.valuesForRequest(ep, req) ++ labels
                      .valuesForResponse(res): _*
                  )
                  .inc()
              )
            }
            .onException { (ep, ex) =>
              m.eval(
                counter
                  .labelValues(
                    labels.valuesForRequest(ep, req) ++ labels
                      .valuesForResponse(ex): _*
                  )
                  .inc()
              )
            }
        }
      }
    )

  def requestDuration[F[_]](
    registry: PrometheusRegistry,
    namespace: String,
    labels: MetricLabels,
    clock: Clock = Clock.systemUTC()
  ): Metric[F, Histogram] =
    Metric[F, Histogram](
      Histogram
        .builder()
        .name(s"${namespace}_request_duration_seconds")
        .help("Duration of HTTP requests")
        .labelNames(
          labels.namesForRequest ++ labels.namesForResponse ++ List(
            labels.forResponsePhase.name
          ): _*
        )
        .register(registry),
      onRequest = { (req, histogram, m) =>
        m.eval {
          val requestStart = clock.instant()
          def duration = Duration
            .between(requestStart, clock.instant())
            .toMillis
            .toDouble / 1000.0
          EndpointMetric()
            .onResponseHeaders { (ep, res) =>
              m.eval(
                histogram
                  .labelValues(
                    labels.valuesForRequest(ep, req) ++ labels
                      .valuesForResponse(res) ++ List(
                      labels.forResponsePhase.headersValue
                    ): _*
                  )
                  .observe(duration)
              )
            }
            .onResponseBody { (ep, res) =>
              m.eval(
                histogram
                  .labelValues(
                    labels.valuesForRequest(ep, req) ++ labels
                      .valuesForResponse(res) ++ List(
                      labels.forResponsePhase.bodyValue
                    ): _*
                  )
                  .observe(duration)
              )
            }
            .onException { (ep, ex) =>
              m.eval(
                histogram
                  .labelValues(
                    labels.valuesForRequest(ep, req) ++ labels
                      .valuesForResponse(ex) ++ List(
                      labels.forResponsePhase.bodyValue
                    ): _*
                  )
                  .observe(duration)
              )
            }
        }
      }
    )
}
```

**Comment by adamw** [comment]
Thanks for the detailed investigation report!

Maybe it would be simplest and best to update the tapir integration module to the latest prometheus client version?

**Comment by adamw** [comment]
@gastonschabas Definitely! PRs are always welcome :)
