### ISSUE TITLE
Runtime error when mixing sealed traits and nested case classes

### ISSUE THREAD

**Issue by redvasily** [softwaremill/tapir#352]
Hi,

I've run into a following error when using tapir. If I have some classes defined like this:

```scala
sealed trait ComplexRequest

case class Foo(id: Int, arg: String)

final case class ComplexRequest1(tag: String, date: String, foo: Foo)
    extends ComplexRequest
```

And a simple endpoint defined like this:

```scala
  val complex = baseEndpoint.post
    .in("complex")
    .in(jsonBody[ComplexRequest])
    .out(jsonBody[SimpleResponse])
```

When I start the server I get a following error:

```
[error] java.lang.ExceptionInInitializerError
[error]         at example.Hello$.startServer(Hello.scala:127)
[error]         at example.Hello$.delayedEndpoint$example$Hello$1(Hello.scala:135)
[error]         at example.Hello$delayedInit$body.apply(Hello.scala:113)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at example.Hello$.main(Hello.scala:113)
[error]         at example.Hello.main(Hello.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.util.NoSuchElementException: key not found: SObjectInfo(example.Foo,List())
[error]         at scala.collection.immutable.Map$Map4.apply(Map.scala:207)
[error]         at tapir.docs.openapi.schema.SchemaReferenceMapper.map(SchemaReferenceMapper.scala:8)
[error]         at tapir.docs.openapi.schema.TSchemaToOSchema.apply(TSchemaToOSchema.scala:45)
[error]         at tapir.docs.openapi.schema.TSchemaToOSchema.$anonfun$apply$1(TSchemaToOSchema.scala:28)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.immutable.List.map(List.scala:298)
[error]         at tapir.docs.openapi.schema.TSchemaToOSchema.apply(TSchemaToOSchema.scala:26)
[error]         at tapir.docs.openapi.schema.ObjectSchemasForEndpoints$.$anonfun$apply$4(ObjectSchemasForEndpoints.scala:19)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.immutable.List.map(List.scala:298)
[error]         at tapir.docs.openapi.schema.ObjectSchemasForEndpoints$.apply(ObjectSchemasForEndpoints.scala:19)
[error]         at tapir.docs.openapi.EndpointToOpenAPIDocs$.toOpenAPI(EndpointToOpenAPIDocs.scala:12)
[error]         at tapir.docs.openapi.TapirOpenAPIDocs$RichOpenAPIEndpoints.toOpenAPI(TapirOpenAPIDocs.scala:18)
[error]         at tapir.docs.openapi.TapirOpenAPIDocs$RichOpenAPIEndpoints.toOpenAPI(TapirOpenAPIDocs.scala:15)
[error]         at example.Documentation$.<init>(Hello.scala:67)
[error]         at example.Documentation$.<clinit>(Hello.scala)
[error]         at example.Hello$.startServer(Hello.scala:127)
[error]         at example.Hello$.delayedEndpoint$example$Hello$1(Hello.scala:135)
[error]         at example.Hello$delayedInit$body.apply(Hello.scala:113)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at example.Hello$.main(Hello.scala:113)
[error]         at example.Hello.main(Hello.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
```

If I define the endpoint to use a case class directly everything works fine:
```scala
  val complex = baseEndpoint.post
    .in("complex")
    .in(jsonBody[ComplexRequest1])
    .out(jsonBody[SimpleResponse])
```

Another way to get this example to run is to remove a nested case class, so the example runs with the following ComplexRequest1 definition:

```scala
final case class ComplexRequest1(tag: String, date: String) extends ComplexRequest
```

Here's a small example repository to reproduce the problem: https://github.com/redvasily/tapir-case-classes-error

**Comment by redvasily** [comment]
I use tapir version from tapir-three example project. Apparently it all works in the latest tapir version: 0.11.9
