### ISSUE TITLE
[BUG] IllegalArgumentException is thrown when calling ResponseEntity.contentLengthOption

### ISSUE THREAD

**Issue by Matzz** [softwaremill/tapir#4138]
Tapir version: 1.9.4

Pekko version: 1.0.2

Scala version: 3.3.3

**Describe the bug**
`IllegalArgumentException` is thrown when calling `ResponseEntity.contentLengthOption` from `sttp.tapir.server.metrics.EndpointMetric.onResponseBody`

**How to reproduce?**

It happens during tests. I didn't narrowed the test code yet but thats the implementation which triggers the error:
```scala

import com.newrelic.api.agent.{MetricAggregator, NewRelic}
import com.typesafe.scalalogging.LazyLogging
import sttp.tapir.server.metrics.{EndpointMetric, Metric}

import scala.concurrent.Future

class NewRelicMetrics(clock: () => Long) extends LazyLogging {

  val newRelicMetric: Metric[Future, MetricAggregator] =
    Metric(
      metric = NewRelic.getAgent.getMetricAggregator(),
      onRequest = (serverRequest, agg, me) =>
        me.eval {
          EndpointMetric(
            onEndpointRequest = None,
            onResponseHeaders = Some((ep, response) => me.eval(()) ),
            onResponseBody = Some((ep, response) => me.eval(()) ),
            onException = Some((ep, throwable) => me.eval(()) ),
          )
        },
    )
}
/.../
private val nrMetrics = NewRelicMetrics(System.currentTimeMillis)
def options(implicit ec: ExecutionContext): PekkoHttpServerOptions =
    PekkoHttpServerOptions.customiseInterceptors
      .exceptionHandler(CustomExceptionHandler.default)
      .decodeFailureHandler(CustomDecodeFailureHandler.default)
      .metricsInterceptor(new MetricsRequestInterceptor(List(nrMetrics.newRelicMetric), Seq.empty))
      .options

/.../
```

**Additional information**

Stack trace:
```
11/06 12:27:02 ERROR[cluster1-nio-worker-2] a.b.c.XYZ$ - Illegal argument exception encountered HttpRequest(HttpMethod(GET),http://XYZ,List(X-Correlation-Id: ABC, X-Client-Req-Id: ABC, Authorization),HttpEntity.Strict(none/none,0 bytes total),HttpProtocol(HTTP/1.1))
java.lang.IllegalArgumentException: requirement failed: contentLength must be positive (use `HttpEntity.empty(contentType)` for empty entities)
	at scala.Predef$.require(Predef.scala:337)
	at org.apache.pekko.http.scaladsl.model.HttpEntity$Default.<init>(HttpEntity.scala:407)
	at org.apache.pekko.http.scaladsl.model.HttpEntity$Default$.apply(HttpEntity.scala:401)
	at org.apache.pekko.http.scaladsl.model.HttpEntity.transformDataBytes(HttpEntity.scala:151)
	at org.apache.pekko.http.scaladsl.model.HttpEntity.transformDataBytes$(HttpEntity.scala:48)
	at org.apache.pekko.http.scaladsl.model.HttpEntity$Strict.transformDataBytes(HttpEntity.scala:361)
	at sttp.tapir.server.pekkohttp.PekkoBodyListener.onComplete(PekkoBodyListener.scala:29)
	at sttp.tapir.server.pekkohttp.PekkoBodyListener.onComplete(PekkoBodyListener.scala:14)
	at sttp.tapir.server.interpreter.BodyListener$BodyListenerOps.onComplete(BodyListener.scala:11)
	at sttp.tapir.server.interceptor.metrics.MetricsEndpointInterceptor.withBodyOnComplete$$anonfun$1(MetricsEndpointInterceptor.scala:127)
	at sttp.monad.syntax$MonadErrorOps.map(MonadError.scala:60)
	at sttp.tapir.server.interceptor.metrics.MetricsEndpointInterceptor.sttp$tapir$server$interceptor$metrics$MetricsEndpointInterceptor$$withBodyOnComplete(MetricsEndpointInterceptor.scala:127)
	at sttp.tapir.server.interceptor.metrics.MetricsEndpointInterceptor$$anon$1.$anonfun$2$$anonfun$2$$anonfun$2$$anonfun$1(MetricsEndpointInterceptor.scala:54)
	at sttp.monad.syntax$MonadErrorOps.map(MonadError.scala:60)
	at sttp.tapir.server.interceptor.metrics.MetricsEndpointInterceptor$$anon$1.$anonfun$2$$anonfun$2$$anonfun$2(MetricsEndpointInterceptor.scala:55)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run$$anonfun$1(BatchingExecutor.scala:110)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run$$anonfun$adapted$1(BatchingExecutor.scala:119)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:119)
	at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
	at org.apache.pekko.testkit.CallingThreadDispatcher.executeTask(CallingThreadDispatcher.scala:249)
	at org.apache.pekko.dispatch.MessageDispatcher.unbatchedExecute(AbstractDispatcher.scala:177)
	at org.apache.pekko.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:140)
	at org.apache.pekko.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:65)
	at org.apache.pekko.dispatch.MessageDispatcher.execute(AbstractDispatcher.scala:107)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run$$anonfun$1(BatchingExecutor.scala:110)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run$$anonfun$adapted$1(BatchingExecutor.scala:119)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:119)
	at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
	at org.apache.pekko.testkit.CallingThreadDispatcher.executeTask(CallingThreadDispatcher.scala:249)
	at org.apache.pekko.dispatch.MessageDispatcher.unbatchedExecute(AbstractDispatcher.scala:177)
	at org.apache.pekko.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:140)
	at org.apache.pekko.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:65)
	at org.apache.pekko.dispatch.MessageDispatcher.execute(AbstractDispatcher.scala:107)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
```

![debug](https://github.com/user-attachments/assets/0b975430-8750-49db-b77d-19728fdcd603)

**Comment by Matzz** [comment]
Closed by https://github.com/softwaremill/tapir/pull/4140
