### ISSUE TITLE
[BUG] Tapir + HTTP4S | NullPointerException in Swagger on Native Image

### ISSUE THREAD

**Issue by atrianac** [softwaremill/tapir#861]
Tapir version: 0.17.0-M8

Scala version: 2.13

**Describe the bug**

Using Tapir + HTTP4S raise an error when `SwaggerHttp4s` is used on GraalVM native image. The error raised is:

`bash
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
        at java.lang.Class.ensureInitialized(DynamicHub.java:499)
        at com.x.x.Main$.<clinit>(Main.scala:29)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at java.lang.Class.ensureInitialized(DynamicHub.java:499)
        at com.adidas.ys.Main.main(Main.scala)
Caused by: java.lang.NullPointerException
        at sttp.tapir.swagger.http4s.SwaggerHttp4s.<init>(SwaggerHttp4s.scala:35)
        at com.adidas.ys.http.server.HttpServer$.<clinit>(HttpServer.scala:46)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        ... 6 more
` 

Note: Looks the problem is on `SwaggerHttp4s` when the resource is loaded at 33L. 

`val pomProperties = getClass.getResourceAsStream("/META-INF/maven/org.webjars/swagger-ui/pom.properties")` [SwaggerHttp4s.scala](https://github.com/softwaremill/tapir/blob/a173fb694f275c8d784e8c40683728962bb68a64/docs/swagger-ui-http4s/src/main/scala/sttp/tapir/swagger/http4s/SwaggerHttp4s.scala)

Presumably the problem is related with: [GraalVM Issue - Relative classpath resource](https://github.com/oracle/graal/issues/2250)

**How to reproduce?**

1. Create a simple app, using Tapir and HTTP4S. The app looks like this:

```scala
object HealthCheckEndpoint {

  val serviceResponse = ZIO
    .environment[ApplicationEnvironment]
    .flatMap(_ => ZIO.succeed("Service Available"))

  val service: ZServerEndpoint[ApplicationEnvironment, Unit, Unit, String] =
    endpoint.get
      .in("health-check")
      .out(stringBody)
      .zServerLogic(_ => serviceResponse)
}
```

```scala
object HttpServer {

 ...

  val httpRoutes: HttpRoutes[RIO[ExtendedEnvironment, *]] =
    List(
      HealthCheckEndpoint.service.widen[ExtendedEnvironment],
    ).toRoutes

  val yamlDocs: String = {
    import sttp.tapir.docs.openapi._
    import sttp.tapir.openapi.circe.yaml._
    val x = List(
      HealthCheckEndpoint.service,
    )
    
    x.toOpenAPI("API Name", "1.0").toYaml
  }

  val httpApp = Router(
    "/" -> (httpRoutes <+> new SwaggerHttp4s(yamlDocs).routes)
  ).orNotFound

  val httpServer =
    ZManaged.runtime[ExtendedEnvironment].flatMap { implicit rts =>
      BlazeServerBuilder[RIO[ExtendedEnvironment, *]](
        rts.platform.executor.asEC
      )
        .bindHttp(8080, "0.0.0.0")
        .withHttpApp(httpApp)
        .resource
        .toManagedZIO
    }

  val httpServerLayer: ZLayer[ExtendedEnvironment, Throwable, ZHttp4sServer] =
    ZLayer.fromManaged(httpServer)
}

```

**Additional information**

I will provide a project example ASAP

**Comment by adamw** [comment]
Maybe this will be useful as a template to extend: https://github.com/usommerl/graalnative4s

**Comment by atrianac** [comment]
> Maybe this will be useful as a template to extend: https://github.com/usommerl/graalnative4s

@adamw @adamw Thanks for the insight, It was very helpful. The `resource-config.json` file is mandatory when some resource is loaded using classpath mechanism. I will publish a similar project template using ZIO.

**Comment by adamw** [comment]
@atrianac please let us know when the template is ready, we'll add a link to the docs :)
